version: '2'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
  proxy_redis:
    image: "redis"
    container_name: proxy_redis
networks:
  default: 
    external: true
    name: crawler-net